### ISSUE TITLE
Battery Tester HW breadboard model

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-EPS#10]
- [x] Build the Battery Discharge tool on a breadboard
- [x] Change the R1 resistor ( @peter-markos )
- [x] Refresh schematics with proper values ( @Bgoczan )

**Comment by Bgoczan** [comment]
@peter-markos please confirm:
R1 resistor is 1K and U<sub>RI</sub> is 2.5V, am I right?

**Comment by peter-markos** [comment]
I confirm. R1 is 1K and URI is 2.5V.
