### ISSUE TITLE
4xAA Battery Characteristics

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-EPS#3]
## Measurement
Use the Battery Tester hardware to measure the discharge characteristics of 4xAA battery pack.

## Documentation
[Battery Characteristics wiki page](https://github.com/legokor/UPRA-EPS/wiki/Battery-Characteristics#4xaa-dry-cells)

**Comment by peter-markos** [comment]
https://github.com/legokor/UPRA-EPS/wiki/4xAA-Discharge-Test-Record
