### ISSUE TITLE
3xAA Battery Characteristics

### ISSUE THREAD

**Issue by Bgoczan** [legokor/UPRA-EPS#4]
## Measurement
Use the Battery Tester hardware to measure the discharge characteristics of 3xAA battery pack.

## Documentation
[Battery Characteristics wiki page](https://github.com/legokor/UPRA-EPS/wiki/Battery-Characteristics#3xaa-dry-cells)

**Comment by peter-markos** [comment]
https://github.com/legokor/UPRA-EPS/wiki/3xAA-Discharge-Test-Record
